#!/usr/bin/expect -f
set timeout 60
set password "eda2020"
set server "EDA@192.168.112.163"

spawn scp $server:/tmp/tmux_pane0.log /tmp/tmux_pane1.log /tmp/test_output.log /Users/luzi/code/hipilot-0.3.0/hipilot/e2e_evidence/

expect "password:"
send "$password\r"

expect eof

# Also download some of the better existing screenshots
spawn scp $server:/tmp/hipilot_test_screen.png /tmp/hipilot_ibex_integration.png /Users/luzi/code/hipilot-0.3.0/hipilot/e2e_evidence/

expect "password:"
send "$password\r"

expect eof
