##############################################################################
# icc2_check_drc.tcl
# HiPilot Template: DRC Checking in Synopsys IC Compiler II
#
# Description:
#   Runs design rule checking within ICC2 using check_routes and
#   report_design -drc_violations. Categorizes violations by type
#   (short, spacing, width, via, antenna) and produces a structured
#   summary report. Intended for post-route DRC sign-off checks.
#
# Usage:
#   source icc2_check_drc.tcl
#   -- or --
#   icc2_shell> source icc2_check_drc.tcl
#
# Prerequisites:
#   - Design must be loaded and routed (post-route)
#   - Technology rules must be loaded with the design library
#   - NDM/tech file with DRC rules must be present
#
# Author:  HiPilot auto-generated template
# Version: 1.0
##############################################################################

##############################################################################
# SECTION 1: PARAMETERS
# Modify these variables to match your design and sign-off requirements.
##############################################################################

# Maximum number of violations to report per category (0 = unlimited)
set max_violations      1000

# Output report file path (will be created/overwritten)
set report_file         "./reports/drc_check.rpt"

# Enable antenna violation checking: 1 = yes, 0 = skip
set check_antenna       1

# Enable connectivity checking (open nets, floating metals): 1 = yes
set check_connectivity  1

# Layers to restrict DRC to (leave empty for all layers)
# Example: "M1 M2 M3 VIA1 VIA2"
set check_layers        ""

# Minimum violation severity to report: "error" | "warning" | "all"
set severity_filter     "all"

# Prefix for all report files generated by this script
set report_prefix       "./reports/drc"

##############################################################################
# SECTION 2: PRE-CHECK
# Verify design is in a valid routed state before running DRC.
##############################################################################

puts "======================================================================"
puts "HiPilot: icc2_check_drc.tcl"
puts "======================================================================"
puts "Parameters:"
puts "  max_violations     = $max_violations"
puts "  report_file        = $report_file"
puts "  check_antenna      = $check_antenna"
puts "  check_connectivity = $check_connectivity"
puts "  check_layers       = [expr {$check_layers eq {} ? {(all layers)} : $check_layers}]"
puts "  severity_filter    = $severity_filter"
puts ""

# Verify a design is open
set current_design_name [get_attribute [current_design] full_name]
if {$current_design_name eq ""} {
    error "ERROR: No design is currently open. Load and route a design first."
}
puts "Pre-check: Design loaded = $current_design_name"

# Verify routing has been performed (check for routed wires)
set routed_nets [sizeof_collection [get_nets -filter "is_routed == true" -quiet]]
set total_nets  [sizeof_collection [get_nets -quiet]]
puts "Pre-check: Routed nets = $routed_nets / $total_nets"
if {$routed_nets == 0} {
    puts "WARNING: No routed nets detected. DRC results will be incomplete."
    puts "         Run route_auto or route_detail before checking DRC."
}

# Create report directory if it does not exist
set report_dir [file dirname $report_prefix]
file mkdir $report_dir
puts "Pre-check: Report directory = $report_dir"
puts ""

##############################################################################
# SECTION 3: ROUTE DRC CHECK
# Run check_routes to identify routing rule violations.
##############################################################################

puts "======================================================================"
puts "STEP 1: Running check_routes (routing DRC)"
puts "======================================================================"

# check_routes verifies all route segments against technology DRC rules.
# -open_net_severity  : treat open nets as errors
# -short_severity     : treat shorts as errors
# -verbose            : detailed violation messages
if {$check_layers ne ""} {
    check_routes \
        -open_net_severity   error \
        -short_severity      error \
        -verbose \
        -layers              $check_layers \
        > "${report_prefix}_routes.rpt"
} else {
    check_routes \
        -open_net_severity   error \
        -short_severity      error \
        -verbose \
        > "${report_prefix}_routes.rpt"
}
puts "  Routing DRC written to: ${report_prefix}_routes.rpt"

##############################################################################
# SECTION 4: DESIGN DRC REPORT
# Use report_design to extract categorized DRC violation counts.
##############################################################################

puts ""
puts "======================================================================"
puts "STEP 2: Reporting design DRC violations (report_design)"
puts "======================================================================"

# report_design -drc_violations produces a categorized breakdown.
# Categories include: shorts, opens, spacing, width, via, antenna, notch.
if {$max_violations > 0} {
    report_design \
        -drc_violations \
        -max_violations $max_violations \
        > "${report_prefix}_design_drc.rpt"
} else {
    report_design \
        -drc_violations \
        > "${report_prefix}_design_drc.rpt"
}
puts "  Design DRC report written to: ${report_prefix}_design_drc.rpt"

##############################################################################
# SECTION 5: ANTENNA VIOLATION CHECK
# Check antenna ratios for all connected nets (gate oxide damage risk).
##############################################################################

if {$check_antenna} {
    puts ""
    puts "======================================================================"
    puts "STEP 3: Checking antenna violations"
    puts "======================================================================"

    # check_antenna verifies that accumulated metal area on each net layer
    # does not exceed the allowable antenna ratio defined in the tech file.
    # Violations indicate risk of gate oxide damage during fabrication.
    check_antenna \
        > "${report_prefix}_antenna.rpt"
    puts "  Antenna report written to: ${report_prefix}_antenna.rpt"
} else {
    puts "STEP 3: Antenna check SKIPPED (check_antenna=0)"
}

##############################################################################
# SECTION 6: CONNECTIVITY CHECK
# Verify all nets are properly connected (no opens or floating wires).
##############################################################################

if {$check_connectivity} {
    puts ""
    puts "======================================================================"
    puts "STEP 4: Checking connectivity (open nets / floating metals)"
    puts "======================================================================"

    # check_routes -open_net captures any nets that are not fully connected.
    # Floating metals are metal segments not connected to any net.
    check_routes \
        -open_net_severity  error \
        -check_same_via_cell true \
        > "${report_prefix}_connectivity.rpt"
    puts "  Connectivity report written to: ${report_prefix}_connectivity.rpt"
} else {
    puts "STEP 4: Connectivity check SKIPPED (check_connectivity=0)"
}

##############################################################################
# SECTION 7: VIOLATION CATEGORIZATION
# Parse and categorize violations from check_routes results.
##############################################################################

puts ""
puts "======================================================================"
puts "STEP 5: Categorizing violations"
puts "======================================================================"

# Read route DRC report and extract violation counts per category
set route_rpt_content [exec cat "${report_prefix}_routes.rpt"]

# Extract counts using string search patterns from ICC2 output format
set short_count    0
set spacing_count  0
set width_count    0
set via_count      0
set open_count     0
set notch_count    0

# ICC2 check_routes output contains lines like:
#   "Total number of DRC violations: N"
#   "Short violations: N"
#   "Spacing violations: N"
foreach line [split $route_rpt_content "\n"] {
    if {[regexp -nocase {short.*?:\s*(\d+)}    $line -> n]} { incr short_count   $n }
    if {[regexp -nocase {spacing.*?:\s*(\d+)}  $line -> n]} { incr spacing_count $n }
    if {[regexp -nocase {width.*?:\s*(\d+)}    $line -> n]} { incr width_count   $n }
    if {[regexp -nocase {via.*?:\s*(\d+)}      $line -> n]} { incr via_count     $n }
    if {[regexp -nocase {open.*?:\s*(\d+)}     $line -> n]} { incr open_count    $n }
    if {[regexp -nocase {notch.*?:\s*(\d+)}    $line -> n]} { incr notch_count   $n }
}

set total_route_viols [expr {$short_count + $spacing_count + $width_count + $via_count + $open_count + $notch_count}]

##############################################################################
# SECTION 8: COMBINED REPORT FILE
# Write structured summary combining all DRC results.
##############################################################################

set rpt_fd [open $report_file w]
puts $rpt_fd "##############################################################################"
puts $rpt_fd "# DRC Check Summary - HiPilot"
puts $rpt_fd "# Design : $current_design_name"
puts $rpt_fd "# Date   : [exec date]"
puts $rpt_fd "##############################################################################"
puts $rpt_fd ""
puts $rpt_fd "VIOLATION CATEGORY SUMMARY"
puts $rpt_fd [format "  %-25s %8s" "Category" "Count"]
puts $rpt_fd [format "  %-25s %8s" [string repeat "-" 25] [string repeat "-" 8]]
puts $rpt_fd [format "  %-25s %8d" "Short"   $short_count]
puts $rpt_fd [format "  %-25s %8d" "Spacing" $spacing_count]
puts $rpt_fd [format "  %-25s %8d" "Width"   $width_count]
puts $rpt_fd [format "  %-25s %8d" "Via"     $via_count]
puts $rpt_fd [format "  %-25s %8d" "Open"    $open_count]
puts $rpt_fd [format "  %-25s %8d" "Notch"   $notch_count]
puts $rpt_fd [format "  %-25s %8d" "TOTAL"   $total_route_viols]
puts $rpt_fd ""
puts $rpt_fd "Detail reports:"
puts $rpt_fd "  Routing DRC   : ${report_prefix}_routes.rpt"
puts $rpt_fd "  Design DRC    : ${report_prefix}_design_drc.rpt"
if {$check_antenna}      { puts $rpt_fd "  Antenna       : ${report_prefix}_antenna.rpt" }
if {$check_connectivity} { puts $rpt_fd "  Connectivity  : ${report_prefix}_connectivity.rpt" }
close $rpt_fd
puts "  Summary written to: $report_file"

##############################################################################
# SECTION 9: QoR SUMMARY OUTPUT
##############################################################################

puts ""
puts "======================================================================"
puts "DRC CHECK SUMMARY"
puts "======================================================================"
puts [format "  %-25s %8s" "Category" "Count"]
puts [format "  %-25s %8s" [string repeat "-" 25] [string repeat "-" 8]]
puts [format "  %-25s %8d" "Short"   $short_count]
puts [format "  %-25s %8d" "Spacing" $spacing_count]
puts [format "  %-25s %8d" "Width"   $width_count]
puts [format "  %-25s %8d" "Via"     $via_count]
puts [format "  %-25s %8d" "Open"    $open_count]
puts [format "  %-25s %8d" "Notch"   $notch_count]
puts [format "  %-25s %8d" "TOTAL"   $total_route_viols]
puts "======================================================================"

if {$total_route_viols == 0} {
    puts "RESULT: DRC CLEAN - No routing violations found."
} else {
    puts "RESULT: $total_route_viols DRC violations found."
    puts "        Review ${report_prefix}_routes.rpt for details."
    puts "        Shorts and opens are blocking; spacing/width may be waivable."
}

puts ""
puts "HiPilot: icc2_check_drc.tcl COMPLETE"
puts "======================================================================"
