/**
 * TestReporter - Generate standardized E2E test reports
 *
 * Creates markdown reports with all evidence and results.
 */

import fs from 'fs';
import path from 'path';

class TestReporter {
  constructor(options = {}) {
    this.testName = options.testName || 'Test';
    this.testDir = options.testDir;
    this.localDir = options.localDir;
    this.timestamp = options.timestamp;
    this.evidenceDir = path.join(this.localDir, 'e2e_evidence', this.timestamp);
  }

  /**
   * Generate test report
   */
  async generate(steps) {
    const report = this.buildReport(steps);
    const reportPath = path.join(this.evidenceDir, 'HITESTBOT_REPORT.md');

    fs.writeFileSync(reportPath, report, 'utf8');
    console.log(`   📄 Report: ${reportPath}`);

    return reportPath;
  }

  buildReport(steps) {
    const passed = steps.filter(s => s.status === 'passed').length;
    const failed = steps.filter(s => s.status === 'failed').length;

    return `# HiTestBot - ${this.testName} Report

**Timestamp:** ${this.timestamp}
**Test Directory:** ${this.testDir || 'N/A'}

## Summary

| Metric | Value |
|--------|-------|
| Total Steps | ${steps.length} |
| Passed | ${passed} ✅ |
| Failed | ${failed} ${failed > 0 ? '❌' : ''} |
| Result | ${failed === 0 ? '✅ PASSED' : '❌ FAILED'} |

## Execution Log

| # | Step | Status | Duration |
|---|------|--------|----------|
${steps.map((s, i) => `| ${i + 1} | ${s.name} | ${s.status === 'passed' ? '✅' : '❌'} | ${s.duration || 'N/A'}s |`).join('\n')}

## Evidence Files

\`\`\`
e2e_evidence/${this.timestamp}/
├── *.mp4          Video recording
├── *.png          Screenshots
├── *_pane.log     Tmux pane captures
└── HITESTBOT_REPORT.md  This report
\`\`\`

## What Was Tested

1. Video recording (ffmpeg x11grab)
2. Code upload and npm install
3. MCP server configuration
4. Tmux workspace setup
5. Innovus startup in right pane
6. Windowed terminal (non-fullscreen)
7. Claude Code startup in left pane
8. HiPilot command execution
9. EDA command execution
10. Evidence capture and download

## Notes

- Video recorded at 2560x1558 @ 20fps
- Windowed terminal (desktop visible)
- Uses C-m (Ctrl+M) for Claude Code commands
- All evidence timestamped

---
*Generated by HiTestBot at ${new Date().toISOString()}*
`;
  }

  /**
   * Generate error report on failure
   */
  generateErrorReport(error, steps) {
    return `# HiTestBot E2E Test - FAILED

**Timestamp:** ${this.timestamp}
**Error:** ${error.message}

## Completed Steps

${steps.map((s, i) => `- ${i + 1}. ${s.name}: ${s.status}`).join('\n')}

## Error Details

\`\`\`
${error.stack}
\`\`\`

---
*Generated by HiTestBot at ${new Date().toISOString()}*
`;
  }
}

export { TestReporter };
